'use client';
/* eslint-disable react-hooks/set-state-in-effect */
/* eslint-disable @next/next/no-img-element */

import { useCallback, useEffect, useRef, useState } from 'react';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
type PlaceStatus = 'visited' | 'wishlist' | 'lived' | 'worked' | 'studied';
interface Album { id: string; image_url: string; caption: string | null; taken_at: string | null; }
interface Visit { id: string; visit_date: string; }
interface PlaceDetail { id: string; name: string; longitude: number; latitude: number; status: PlaceStatus; visits: Visit[]; description: string | null; country: string; province: string; created_at: string; albums: Album[]; }
interface FormValues { name: string; longitude: string; latitude: string; status: PlaceStatus; visitDate: string; description: string; }

const fromPlace = (place: PlaceDetail): FormValues => ({ name: place.name, longitude: String(place.longitude), latitude: String(place.latitude), status: place.status, visitDate: place.visits?.[0]?.visit_date || '', description: place.description || '' });

export default function PlaceDetailPanel({ placeId, onClose, onDeleted }: { placeId: string; onClose: () => void; onDeleted: () => void }) {
  const imageInput = useRef<HTMLInputElement>(null); const [place, setPlace] = useState<PlaceDetail | null>(null); const [values, setValues] = useState<FormValues | null>(null); const [newVisitDate, setNewVisitDate] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await fetch(`${API_URL}/places/${placeId}`); if (!response.ok) throw new Error('Unable to load place details.'); const data = await response.json() as PlaceDetail; setPlace(data); setValues(fromPlace(data)); }, [placeId]);
  useEffect(() => { setLoading(true); void load().catch((cause) => setError(cause instanceof Error ? cause.message : 'Unable to load place details.')).finally(() => setLoading(false)); }, [load]);
  const update = <K extends keyof FormValues>(key: K, value: FormValues[K]) => setValues((current) => current ? { ...current, [key]: value } : current);
  const reload = async () => { try { await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to refresh place.'); } };
  async function addVisit() { if (!newVisitDate) return setError('Choose a visit date.'); const response = await fetch(`${API_URL}/places/${placeId}/visits?visit_date=${newVisitDate}`, { method: 'POST' }); if (!response.ok) return setError('Unable to add visit.'); setNewVisitDate(''); await reload(); }
  async function removeVisit(visitId: string) { const response = await fetch(`${API_URL}/places/${placeId}/visits/${visitId}`, { method: 'DELETE' }); if (!response.ok) return setError('Unable to remove visit.'); await reload(); }
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!values) return; const longitude = Number(values.longitude); const latitude = Number(values.latitude); if (!values.name.trim()) return setError('Place name is required.'); if (!Number.isFinite(longitude) || longitude < -180 || longitude > 180 || !Number.isFinite(latitude) || latitude < -90 || latitude > 90) return setError('Coordinates are invalid.'); setSaving(true); setError(null); try { const response = await fetch(`${API_URL}/places/${placeId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: values.name.trim(), longitude, latitude, status: values.status, description: values.description.trim() || null }) }); if (!response.ok) throw new Error(`Unable to save place (${response.status}).`); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save place.'); } finally { setSaving(false); } }
  async function removePlace() { if (!place || !window.confirm(`Delete "${place.name}"? This cannot be undone.`)) return; setSaving(true); try { const response = await fetch(`${API_URL}/places/${placeId}`, { method: 'DELETE' }); if (!response.ok) throw new Error('Unable to delete place.'); onDeleted(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to delete place.'); setSaving(false); } }
  async function uploadImages() { const files = imageInput.current?.files; if (!files?.length) return setError('Choose at least one image.'); setUploading(true); setError(null); try { for (const image of Array.from(files)) { const body = new FormData(); body.append('image', image); const response = await fetch(`${API_URL}/places/${placeId}/albums`, { method: 'POST', body }); if (!response.ok) throw new Error(`Unable to upload ${image.name}.`); } if (imageInput.current) imageInput.current.value = ''; await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to upload images.'); } finally { setUploading(false); } }
  async function deleteImage(albumId: string) { if (!window.confirm('Delete this image?')) return; const response = await fetch(`${API_URL}/places/${placeId}/albums/${albumId}`, { method: 'DELETE' }); if (!response.ok) return setError('Unable to delete image.'); await reload(); }
  if (loading && !place) return <p className="detail-loading">Loading place details...</p>;
  if (!place || !values) return <p className="form-error">{error || 'Place details unavailable.'}</p>;
  return <><div className="detail-header"><div><p className="detail-location">{place.province}, {place.country}</p><h2 className="detail-name">{place.name}</h2></div><button className="detail-close" type="button" onClick={onClose}>x</button></div><span className={`status-badge ${place.status}`}>{place.status}</span><form className="detail-editor" onSubmit={save}><label>Name<input value={values.name} onChange={(event) => update('name', event.target.value)} maxLength={300} /></label><div className="form-grid detail-location-grid"><label>Longitude<input value={values.longitude} onChange={(event) => update('longitude', event.target.value)} /></label><label>Latitude<input value={values.latitude} onChange={(event) => update('latitude', event.target.value)} /></label><label>Status<select value={values.status} onChange={(event) => update('status', event.target.value as PlaceStatus)}><option value="visited">Visited</option><option value="wishlist">Wishlist</option><option value="lived">Lived</option><option value="worked">Worked</option><option value="studied">Studied</option></select></label></div><section className="detail-visits"><h3>Visits ({place.visits?.length || 0})</h3><div className="visit-form-row"><input type="date" value={newVisitDate} onChange={(event) => setNewVisitDate(event.target.value)} /><button type="button" onClick={() => void addVisit()}>Add visit</button></div>{place.visits?.length ? <ul className="visit-dates-list">{place.visits.map((visit) => <li key={visit.id}>{visit.visit_date}<button type="button" onClick={() => void removeVisit(visit.id)}>x</button></li>)}</ul> : null}</section><label>Description<textarea rows={3} value={values.description} onChange={(event) => update('description', event.target.value)} /></label>{error && <p className="form-error">{error}</p>}<div className="detail-actions"><button type="submit" disabled={saving}>{saving ? 'Saving...' : 'Save changes'}</button><button type="button" className="danger-link" onClick={removePlace} disabled={saving}>Delete place</button></div></form><section className="detail-photos"><h3>Photos ({place.albums.length})</h3><div className="detail-upload"><input ref={imageInput} type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple /><button type="button" onClick={() => void uploadImages()} disabled={uploading}>{uploading ? 'Uploading...' : 'Upload'}</button></div>{place.albums.length > 0 && <div className="detail-albums">{place.albums.map((album) => <figure key={album.id}><img src={`${API_URL}${album.image_url}`} alt={album.caption || place.name} /><button type="button" onClick={() => void deleteImage(album.id)}>Delete</button></figure>)}</div>}</section></>;
}
